### ISSUE TITLE
Feature : git mv folders too

### ISSUE THREAD

**Issue by paulalbertdev** [adam8810/vscode-git-rename#4]
Hi ! 
Could you add the ability to rename a folder with "git mv" too ? 
Thanks a lot !

**Comment by ketanhdoshi** [comment]
Agreed, would love to have this feature as well

**Comment by runfaj** [comment]
I installed the extension just to rename folders. Alas it doesn't support this :(

**Comment by adam8810** [comment]
Folder renaming has been added to version 1.2.0! Enjoy!

**Comment by paulalbertdev** [comment]
Wow thanks !
