### ISSUE TITLE
Doesn't work with git submodules

### ISSUE THREAD

**Issue by banuni** [adam8810/vscode-git-rename#5]
Well, tried to use it in a git submodule and it thinks that it's not under version control.

not sure what is the solution to this, maybe try to cd to the file's folder before attempting the git-mv.

**Comment by jan-dolejsi** [comment]
Looks like we need to change the cwd to the sub. Fix proposed in PR #12

**Comment by adam8810** [comment]
@jan-dolejsi's PR has been merged and published. Please confirm this is fixed for you once you receive v1.3.0

**Comment by jan-dolejsi** [comment]
Works. Issue may be closed.
