### ISSUE TITLE
Does not honor VSCode 'git.path' setting for Git executable

### ISSUE THREAD

**Issue by ketanhdoshi** [adam8810/vscode-git-rename#6]
I just installed git-rename and tried to run it to rename a file. However, it gives me an error `git is not recognized as an internal or external command, operable program or batch file.`

The Git executable is not on the Windows system PATH, but is defined within VSCode in the `git.path` setting. VSCode is able to find it with no problems and execute all my Git commands, either through the UI or a Terminal.

Git-Rename should use that same setting.

**Comment by adam8810** [comment]
Will add this in next version. Thanks for the feedback.

**Comment by jan-dolejsi** [comment]
Fix proposed in the PR #12

**Comment by adam8810** [comment]
@jan-dolejsi's PR has been merged and published. Please confirm this is fixed for you once you receive v1.3.0

**Comment by jan-dolejsi** [comment]
I could not test this.
